language: python
sudo: false

python:
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - TASK=lint
    - TASK=py27
    - TASK=py34
    - TASK=py35
    - TASK=py36

script:
  - tox -e $TASK

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
