language: python
sudo: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - python: 3.6
      env: TOXENV=lint
    - python: 2.7
      env: TOXENV=27
    - python: 3.4
      env: TOXENV=34
    - python: 3.5
      env: TOXENV=35
    - python: 3.6
      env: TOXENV=36

script:
  - tox

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
