language: python
sudo: false

python:
  - "3.5"

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - TASK=py27
    - TASK=py33
    - TASK=py34
    - TASK=py35
    - TASK=lint

script:
  - tox -e $TASK

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
