language: python
sudo: false

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

cache:
  directories:
    - $HOME/.cache/pip

env:
  matrix:
    - TASK=lint

script:
  - tox -e $TASK

install:
  - "pip install -U pip setuptools"
  - "pip install -U tox"
